services:
  - type: web
    name: alarm-plan-demo
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 20
